devinit/DIwebsite-redesign

- deploy.sh
Thoughts? We'll actually need to replace `/home/di_website/deploy.sh` with this file before merging this. But I'd like to keep the sh up to date in the repo.
> Don't erase project dir

- .editorconfig
- di_website/templates/includes/partials/project.html
- Need this for both #7 and #93
> Reusable project template

- di_website/templates/includes/cards/card-blog.html
- di_website/templates/includes/cards/card-event.html
- di_website/templates/includes/cards/card-news.html
- di_website/templates/includes/cards/card-related.html
> [Update] default card images

- di_website/common/base.py
- di_website/templates/includes/scaffold/pagination.html
Came up with a pretty good algorithm based on Fffunction's designs. Screenshots of behavior below:
> Pretty pagination

- di_website/templates/includes/heroes/hero-news.html
- di_website/templates/includes/heroes/hero-post.html
- di_website/templates/includes/heroes/hero.html
Specifically, orients the author to the right...
> [Update] hero_class block on hero template

- di_website/common/management/commands/importwp.py
Easy class swap for a decently styled download link:
> Replace button class

- di_website/about/models.py
- di_website/blog/models.py
- di_website/contactus/models.py
- di_website/events/models.py
- di_website/news/models.py
- di_website/ourteam/models.py
- di_website/place/models.py
- di_website/project/models.py
- di_website/publications/models.py
- di_website/vacancies/models.py
- di_website/whatwedo/models.py
Added general page as a sub page of every other page.
> Make general page a subpage of all pages

- .travis.yml
@akmiller01 tested it thoroughly this time, so I'm sure it'll work. On top of the `-o` requirement, I had to restart `ssh` on the server to get it to accept the new config.
> Fix SendEnv setting on travis deploy script

- .travis.yml
> Removed multiline bash separator

- di_website/templates/blog/blog_article_page.html
- di_website/templates/includes/heroes/hero-post.html
- di_website/templates/includes/partials/multi-authors.html
> Fix author markup

- .travis.yml
- deploy.sh
- di_website/settings/base.py
- di_website/settings/dev.py
- di_website/settings/production.py
- di_website/wsgi.py
> Merge to Staging

- config/nginx/django.conf
- docker-compose.yml
Working config on Coms staging
> Corrected root file locations for nginx

- di_website/templates/includes/partials/focus_areas.html
> Fix key project links on focus areas page 

- di_website/templates/blocks/banner/banner_block.html
> Fix banner markup for images and embeds

- di_website/templates/ourteam/our_team_page.html
> Fix our team secondary menu

- di_website/templates/includes/heroes/hero_home.html
> Fix hero_home button

- di_website/datasection/models.py
> Add paginator range for dataset listing

- di_website/publications/models.py
- di_website/templates/publications/chapter-nav/nav-item.html
Fix to bug "Read whole chapter one"
> Label types

- di_website/datasection/models.py
- di_website/templates/datasection/dataset_page.html
Because I never guessed that a page would be considered a sibling of itself.
> Fix self relation

- di_website/downloads/models.py
Fix for [#471](https://github.com/devinit/DIwebsite-redesign/issues/471)
> Add search field to publication downloads snippet

- di_website/templates/ourteam/our_team_page.html
Fix for [457](https://github.com/devinit/DIwebsite-redesign/issues/457)
> Change default title for our team filter

- di_website/about/templatetags/count_columns.py
- di_website/templates/about/who_we_are_page.html
Fix for [#410](https://github.com/devinit/DIwebsite-redesign/issues/410)
> Add template tag to set column class based on number of office locations

- di_website/common/templatetags/string_utils.py
- di_website/templates/about/who_we_are_page.html
- di_website/templates/blocks/documentboxsection_block.html
- di_website/templates/blocks/duo_body_block_img.html
- di_website/templates/blocks/duo_body_block_vid.html
- di_website/templates/blocks/expertise.html
- di_website/templates/blocks/locations_map.html
- di_website/templates/blocks/paragraph_block.html
- di_website/templates/blocks/richtext_column.html
- di_website/templates/blocks/section_paragraph_block.html
- di_website/templates/contactus/includes/contact_details.html
- di_website/templates/home/blocks/featured_content.html
- di_website/templates/includes/heroes/hero-pubs.html
- di_website/templates/includes/heroes/hero_home.html
- di_website/templates/includes/partials/accordion.html
- di_website/templates/includes/partials/testimonial.html
- di_website/templates/news/news_index_page.html
- di_website/templates/workforus/work_for_us_page.html
> Replace richtext_strip_wrapper with content filter

- di_website/templates/contactus/contact_page.html
> Add hero--minor to contact-page

- di_website/home/models.py
So many specifics required to get this right.
> Hotfix homepage inherited image

- di_website/templates/includes/cards/card-event.html
> Fix card-event time format

- di_website/templates/vacancies/vacancy_index_page.html
Fix for [#525](https://github.com/devinit/DIwebsite-redesign/issues/525)
> Show message for empty vacancy list

- di_website/datasection/models.py
- di_website/publications/mixins.py
- di_website/publications/models.py
- di_website/templates/datasection/dataset_page.html
- di_website/templates/downloads/download-list.html
> Datasets and figures in publications

- di_website/templates/includes/forms/dataset-filter.html
> Update title for country select filter

- di_website/templates/includes/forms/publication-filter.html
Fix for [#497](https://github.com/devinit/DIwebsite-redesign/issues/497)
> Update titles for select filters on publication listing page

- patterns/converted-html/page-templates/04-our-story.html
- patterns/models/timeline.json
- patterns/templates/page-templates/04-our-story.html
> updated out story timeline to show different date variations

- di_website/users/models.py
> Make JobTitle searchable #583

- di_website/templates/datasection/includes/partials/dataset_body.html
- di_website/templates/includes/cards/card-blog.html
- di_website/templates/includes/heroes/hero-post.html
- di_website/templates/includes/partials/author.html
> Switch to div author template for unpublished or missing author pages

- di_website/templates/blocks/timeline_carousel.html
> Show timeline month/year conditionally

- di_website/settings/production.py
Otherwise we'll get an email on every deploy, I imagine.
> 0.0.0.0 on allowed hosts

- di_website/settings/production.py
We'll also need to remove 159.65.56.142 once we're up on the domain name.
> Disable email logging for DisallowedHost

- di_website/templates/includes/heroes/hero.html
- di_website/templates/includes/partials/author-link.html
Fix for [#519](https://github.com/devinit/DIwebsite-redesign/issues/519)
> Update blog author image dimensions and alignment

- di_website/publications/mixins.py
- di_website/publications/models.py
> Reuse GNR unique page mixin in publication summary page

- di_website/common/templatetags/string_utils.py
I hope this fixes issue #492 ... had trouble replicating the issue, but this is the big difference I found
> Update rich text cleaner to replace <p>\s*</p>

- docker-compose.yml
Allow auto restart on server restart
> Auto restart on server restart

- di_website/templates/publications/legacy_publication_page.html
- di_website/templates/publications/publication_chapter_page.html
- di_website/templates/publications/publication_page.html
> Add pattern html for publication pages

- di_website/settings/base.py
- di_website/templates/layouts/default.html
- di_website/templates/publications/legacy_publication_page.html
- di_website/templates/publications/publication_chapter_page.html
- di_website/templates/publications/publication_page.html
- requirements.txt
This will require some testing on dev first, but in theory it should end up looking like the pattern library.
> Nest author in first loop block, rather than outside

- di_website/settings/base.py
Solution for 
```
The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
```
> Increase maximum fields to 10,000

- di_website/datasection/models.py
> Only filter countries that have datasets

- di_website/templates/publications/legacy_publication_page.html
- di_website/templates/publications/publication_chapter_page.html
> Fix author display for legacy and short publications

- config/nginx/django.conf
> Update django.conf with mouseflow hash fix #750

- di_website/templates/includes/cards/card-spotlights.html
> Fix | country spotlight images

- di_website/templates/publications/chapter-nav/nav.html
Fix for [this comment](https://github.com/devinit/DIwebsite-redesign/issues/757#issuecomment-643271235)
> Rename view full report to view full publication

- di_website/publications/models.py
- di_website/templates/publications/publication_chapter_page.html
Hot fix for narrow publication content
> Fix narrow content in publications

- di_website/templates/blocks/basic_infographic.html
- di_website/templates/publications/blocks/infographic.html
> Make inforgraphic image popup on click

- di_website/downloads/models.py
> Add searchbox to data downloads

- di_website/templates/publications/blocks/rich_text.html
- di_website/templates/publications/publication_appendix_page.html
- di_website/templates/publications/publication_chapter_page.html
- di_website/templates/publications/publication_summary_page.html
- di_website/templates/publications/short_publication_page.html
- Add missing class for first section which add extra padding to top (`section--post`)
- Set the first paragraph of the first RichText block to bold
Fixes [this comment](https://github.com/devinit/DIwebsite-redesign/issues/795#issuecomment-646006216)
> Fix | publication templates

- di_website/downloads/models.py
Unable to index file.title or file__title, so this was the next best solution.
> Add title on save to downloads

- di_website/templates/blocks/banner/richtext.html
- di_website/templates/datasection/tools_banner_block.html
Buttons on banners were not showing in the mobile view.
> Fix | data section design

- di_website/templates/includes/cards/card-blog.html
- di_website/templates/includes/partials/author-card.html
- di_website/templates/includes/partials/author.html
> Use separate template for blog card authors

- di_website/blog/models.py
- di_website/publications/models.py
> Only load public resources pages

- di_website/templates/includes/partials/author-card.html
> Add blog image as background on listing card

- di_website/publications/models.py
> Add related content to the foreword

- di_website/common/base.py
- di_website/home/models.py
- di_website/templates/blocks/full_width_embed.html
- di_website/templates/blocks/section_blockquote.html
- di_website/templates/blocks/section_paragraph_block.html
- di_website/templates/publications/audio_visual_media.html
> Fix | include audio visual media pages on home hero

- di_website/templates/downloads/download-list.html
Fix for [this](https://github.com/devinit/DIwebsite-redesign/issues/870#issuecomment-665728759) comment
> Group publication downloads under one heading

- .github/workflows/workflow.yml
- deploy.sh
- short_deploy.sh
https://bluegreen.devinit.org/
> Run blue green deployment with https server

- di_website/blog/models.py
- di_website/home/models.py
> add audio visual media content on blog and home pages

- di_website/common/templatetags/string_utils.py
- di_website/templates/blocks/documentbox_block.html
- di_website/templates/blocks/documentboxsection_block.html
- di_website/whatwedo/models.py
- requirements.txt
Issue #896 
The `StandardPage` already has what is required, so I changed the `subpage_type` for the `ServicesPage` from `GeneralPage` to `StandardPage`
> Fix | services page children

- di_website/templates/events/event_page.html
> Event social sharing

- di_website/templates/includes/heroes/hero-pubs-short.html
> Show parent title for summary pages

- .github/workflows/workflow.yml
Update environment variables in git workflow.
More info [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
And [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)
> Update environment variables for git workflow

- di_website/templates/publications/footnotes.html
Update based on https://github.com/devinit/DIwebsite-redesign/issues/917#issuecomment-744452330
> Show five publication footnotes by default

- di_website/templates/includes/heroes/hero-post.html
> Fix broken author link in blogs

- di_website/settings/base.py
Update elastic search to auto index so that new publications can be searched after being published #931
> Auto index

- di_website/templates/publications/footnotes.html
> Make button visible when more than 5 footnotes

- di_website/blog/models.py
- di_website/templates/contactus/includes/contact_details.html
Update UK address & Issue #964
> Update UK address

- src/components/ApacheChart/ApacheChart.tsx
- src/components/ApacheChart/utils/index.ts
- src/components/DashboardSection/DashboardSection.tsx
- src/components/HiddenMediaCaption/HiddenMediaCaption.tsx
- src/components/HiddenMediaCaption/index.ts
- src/components/MediaCaption/MediaCaption.tsx
- src/components/MediaCaption/index.ts
- src/dashboard/Dashboard.tsx
- src/dashboard/utils/chart/events.ts
- src/dashboard/utils/chart/index.ts
- src/dashboard/utils/dashboards/pm.ts
- src/dashboard/utils/index.ts
- src/utils/types/dashboard.d.ts
> Feature | Project Management Dashboard

- package-lock.json
- package.json
- src/dashboard/Dashboard.tsx
- src/dashboard/utils/dashboards/fundraising.ts
- src/dashboard/utils/index.ts
- src/utils/types/dashboard.d.ts
- webpack.config.js
Data didn't seem suited for a chart as it was only for Q1 2021, so...
> Feature | Funding Dashboard

- src/dashboard/Dashboard.tsx
- src/dashboard/utils/dashboards/comms.ts
- src/dashboard/utils/dashboards/hr.ts
- src/dashboard/utils/dashboards/pm.ts
> Feature | HR Dashboard

- di_website/templates/publications/blocks/case_study.html
> Share section on case studies

- di_website/templates/includes/scaffold/footer-assets.html
- di_website/templates/tags/cookie_notice.html
- src/notice/index.ts
- webpack.config.js
> Add handling for notices

- di_website/publications/models.py
Make website search for resources less sensitive #1031
> Feature | Update search

- dependabot.yml
Add dependabot config file. Update libraries monthly.
> Update dependabot config file

- di_website/ourteam/templatetags/team_tags.py
>  Order team member user-content by date

- README.md
- di_website/templates/includes/cards/card-job.html
- docker-compose.yml
Making some details on role profiles optional to avoid gaps on the vacancy listing page #1084
> Feature | Optional Vacancy Role Profiles

- .github/workflows/workflow.yml
- README.md
- di_website/common/static/common/js/anchor.js
- di_website/publications/wagtail_hooks.py
- docker-compose.dev.yml
- docker-compose.minimal.yml
> Add Elastic Search on docker dev

- README.md
- docker-compose.dev.yml
- docker-compose.yml
> Fix | Broken Link Checker

- di_website/publications/models.py
- di_website/publications/templatetags/report_utils.py
- di_website/templates/publications/chapter-nav/prev-next.html
- di_website/templates/publications/publication_appendix_page.html
- di_website/templates/publications/publication_chapter_page.html
- di_website/templates/publications/publication_foreword_page.html
- di_website/templates/publications/publication_summary_page.html
> Feature/Improve Bottom Menu for Multi chapter Publications

- requirements.txt
> Upgrade wagtaillinkchecker to 0.5.3

- di_website/publications/models.py
- di_website/templates/publications/chapter-nav/prev-next.html
- di_website/templates/publications/publication_appendix_page.html
- di_website/templates/publications/publication_chapter_page.html
- di_website/templates/publications/publication_foreword_page.html
- di_website/templates/publications/publication_summary_page.html
> Update labels for bottom right publication menu

- di_website/publications/models.py
> Feature/Related Content Executive Summary

- di_website/templates/publications/blocks/interactive_chart.html
Add class to track gha charts in gtm
> Feature | Add GTM Classes

- di_website/common/mixins.py
>  Add twitter card type in metadata

- di_website/common/base.py
> Fix | Copy Pages

- di_website/templates/layouts/default.html
> Use pageurl tag for alias canonical link

- .github/workflows/deploy_CI.yml
> Feature | Deploy Tags

- di_website/common/static/common/js/anchor.js
- di_website/footnotes/templatetags/footnotes_utils.py
- di_website/publications/wagtail_hooks.py
- di_website/templates/includes/partials/anchor.html
- di_website/templates/includes/scaffold/footer-assets.html
Ticket #1249 
This is deployed on staging and there's a video of how it works in a comment on the ticket.
> Feature | Richtext Anchor

- di_website/templates/includes/heroes/hero-pubs-short.html
> Show hero text on short publications

- di_website/common/base.py
> Feature | Order Related Content By Date

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Update Github issue templates

- di_website/publications/mixins.py
- requirements.txt
> Fix | Published Date Bug

- di_website/settings/base.py
- di_website/templates/publications/blocks/so_what.html
> Feature | So What Author Box Edits

- di_website/publications/mixins.py
From this [comment](https://github.com/devinit/DIwebsite-redesign/issues/1306#issuecomment-1583004093)
> Feature | Remove Alias Pages from Related Content

- di_website/templates/datasection/includes/partials/dataset_body.html
- di_website/templates/downloads/blocks/item.html
- di_website/templates/downloads/blocks/item_date.html
- di_website/templates/downloads/blocks/item_image.html
- di_website/templates/downloads/download-list.html
- di_website/templates/publications/blocks/downloads.html
- di_website/templates/publications/data-downloads.html
- di_website/templates/publications/downloads.html
- di_website/templates/vacancies/vacancy_page.html
Ticket #1328 
Deployed and tested on staging
> Fix | No File Error

- di_website/templates/blocks/banner/banner_block.html
>  Maintain theme button border and text color in light banner

- .github/workflows/deploy_CI.yml
This separates prod and staging secrets.
> Update dev and prod secrets

- di_website/templates/includes/partials/multi-authors.html
>  Remove hyperlink for auhtors wihtout live pages

- README.md
- di_website/settings/base.py
- requirements.txt
> Add 2fa to website CMS

- di_website/templates/home/home_page.html
Thought this might be something nice for any developer that opens their console on our home page @wakibi . Hope you're doing alright.
> Base64 encoded memorial
